id: IADC12493
source: https://www.lotsawahouse.org
source_file: null
initial_creation_type: input
imported: '2022-05-30T20:40:41.320188'
last_modified: '2022-05-30T20:40:41.320199'
parser: null
source_metadata:
  title: Fifth Dodrupchen Rinpoche Series
  language: en
  description: 'Texts by and about the Fifth Dodrupchen Rinpoche, Jigme Long-yang
    (''jigs med klong yangs, b. 1962):'
  volume:
    f2624:
      title: Prayer for Swift Rebirth of the Fourth Dodrupchen Rinpoche, Tupten Trinlé
        Palzangpo
      base_file: f2624.txt
      order: 1
      parent: Swift Rebirth Prayers
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
